### ISSUE TITLE
Use OSM login for MapSwipe application

### ISSUE THREAD

**Issue by vlotorev** [mapswipe/app-feedback#30]
Currently MapSwipe requires creating login and password. Missing Maps project is tightly coupled with OpenStreetMap project so it would easier for OSM users if MapSwipe could use OSM login.

**Comment by harry-wood** [comment]
I agree it would be good to offer OSM login as an alternative (dinky little button).

A lot of OpenStreetMap mappers might like to use that. It's worth noting that the real power of MapSwipe is to get people on board who are _not_ already OpenStreetMappers (often because editing OpenStreetMap is too complicated). Even so I think this is a sensible thing to have as an option.

**Comment by laurentS** [comment]
Moved to main mapswipe repo
