### ISSUE TITLE
Suggestion: add direct link to download APK

### ISSUE THREAD

**Issue by nlykl** [mapswipe/app-feedback#8]
Please add direct link to download APK, because some people don't use Google Play.

**Comment by ltog** [comment]
I support this request. I guess that people willing to support MapSwipe would be overproportionally often (compared to all Android users) be technically minded people with an aversion against Google Play, e.g. Fairphone users. (Fairphone provides an Android version that is easy rootable but because of this doesn't contain Google Play.)

Since, in order to publish in Google Play, one has to create APK files anyway, the additional effort to publish these also on the website should be minimal...

**Comment by PimDeWitte** [comment]
added to mapswipe.org
